
import java.awt.Color;
import javax.swing.JFrame;


public class Acceuil_principale extends javax.swing.JFrame {
    Color DefaultColor,ClickedColor;

    /**
     * Creates new form Acceuil_principale
     */
    public Acceuil_principale() {
        super("Gestion_copie");
        initComponents();
        
        DefaultColor=new Color(153, 0, 204);
        ClickedColor=new Color(1,128,128);
        //DefaultColor=new Color(13,36,51);
        //ClickedColor=new Color(240,151,57);
        
        // set default color to pan on run time
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(DefaultColor);
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(DefaultColor); 
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Modifier = new javax.swing.JPanel();
        ModifierPrincipal = new javax.swing.JLabel();
        Acceuil = new javax.swing.JPanel();
        AcceuilPrincipal = new javax.swing.JLabel();
        Saisie = new javax.swing.JPanel();
        SaisiePricipal = new javax.swing.JLabel();
        Consulte = new javax.swing.JPanel();
        ConsultationPrincipal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        minimized = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_XING_100px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, 159, 159));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LA MAIRIE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 186, 218, 35));

        Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ModifierMousePressed(evt);
            }
        });

        ModifierPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ModifierPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/modifier.png"))); // NOI18N
        ModifierPrincipal.setText("   Modifier");
        ModifierPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        ModifierPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierPrincipalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ModifierPrincipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ModifierLayout = new javax.swing.GroupLayout(Modifier);
        Modifier.setLayout(ModifierLayout);
        ModifierLayout.setHorizontalGroup(
            ModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ModifierPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ModifierLayout.setVerticalGroup(
            ModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ModifierPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 230, 60));

        Acceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AcceuilMousePressed(evt);
            }
        });

        AcceuilPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AcceuilPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AccueilBlanc.png"))); // NOI18N
        AcceuilPrincipal.setText("     Acceuil");
        AcceuilPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        AcceuilPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceuilPrincipalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AcceuilPrincipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout AcceuilLayout = new javax.swing.GroupLayout(Acceuil);
        Acceuil.setLayout(AcceuilLayout);
        AcceuilLayout.setHorizontalGroup(
            AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AcceuilLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AcceuilPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AcceuilLayout.setVerticalGroup(
            AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AcceuilPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Acceuil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, 60));

        Saisie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SaisieMousePressed(evt);
            }
        });

        SaisiePricipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaisiePricipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/saisie.png"))); // NOI18N
        SaisiePricipal.setText("     Saisie");
        SaisiePricipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        SaisiePricipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaisiePricipalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SaisiePricipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout SaisieLayout = new javax.swing.GroupLayout(Saisie);
        Saisie.setLayout(SaisieLayout);
        SaisieLayout.setHorizontalGroup(
            SaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SaisieLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SaisiePricipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SaisieLayout.setVerticalGroup(
            SaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SaisiePricipal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Saisie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 230, 60));

        Consulte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConsulteMousePressed(evt);
            }
        });

        ConsultationPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConsultationPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/consulte.png"))); // NOI18N
        ConsultationPrincipal.setText("    Consultation");
        ConsultationPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        ConsultationPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultationPrincipalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConsultationPrincipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ConsulteLayout = new javax.swing.GroupLayout(Consulte);
        Consulte.setLayout(ConsulteLayout);
        ConsulteLayout.setHorizontalGroup(
            ConsulteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsulteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ConsultationPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ConsulteLayout.setVerticalGroup(
            ConsulteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsultationPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Consulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 230, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image/close.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel2.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, -1));

        minimized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image/minimize.png"))); // NOI18N
        minimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizedMouseClicked(evt);
            }
        });
        jPanel2.add(minimized, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Moyen repide et simple ,efficace");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 230, 60));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GESTION COPIE DE NAISSANCE");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 350, 60));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image/sep2.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 50, -1, 370));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/co_working.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 320, 340));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/news.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 340, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void AcceuilPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilPrincipalMousePressed
        // TODO add your handling code here: 
         
    }//GEN-LAST:event_AcceuilPrincipalMousePressed

    private void SaisiePricipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaisiePricipalMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SaisiePricipalMousePressed

    private void ConsultationPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultationPrincipalMousePressed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_ConsultationPrincipalMousePressed

    private void ModifierPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierPrincipalMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ModifierPrincipalMousePressed

    private void AcceuilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(ClickedColor);
        Saisie.setBackground(DefaultColor); 
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(DefaultColor); 
    }//GEN-LAST:event_AcceuilMousePressed

    private void SaisieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaisieMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(ClickedColor); 
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(DefaultColor);
    }//GEN-LAST:event_SaisieMousePressed

    private void ConsulteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsulteMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(DefaultColor); 
        Consulte.setBackground(ClickedColor);
        Modifier.setBackground(DefaultColor);
    }//GEN-LAST:event_ConsulteMousePressed

    private void ModifierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(DefaultColor); 
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(ClickedColor);
    }//GEN-LAST:event_ModifierMousePressed

    private void AcceuilPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilPrincipalMouseClicked
        // TODO add your handling code here:
        //setVisible(false);
        //Acceuil_principale ob= new Acceuil_principale();
        //ob.setVisible(true);   
        
    }//GEN-LAST:event_AcceuilPrincipalMouseClicked

    private void SaisiePricipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaisiePricipalMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        Saisie_copie_principal ob= new Saisie_copie_principal();
        ob.setVisible(true); 
    }//GEN-LAST:event_SaisiePricipalMouseClicked

    private void ConsultationPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultationPrincipalMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        ConsultationPrincipal ob= new ConsultationPrincipal();
        ob.setVisible(true);
    }//GEN-LAST:event_ConsultationPrincipalMouseClicked

    private void ModifierPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierPrincipalMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        ModificationPrincipal ob= new ModificationPrincipal();
        ob.setVisible(true);
    }//GEN-LAST:event_ModifierPrincipalMouseClicked

    private void minimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizedMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizedMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil_principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acceuil;
    private javax.swing.JLabel AcceuilPrincipal;
    private javax.swing.JLabel ConsultationPrincipal;
    private javax.swing.JPanel Consulte;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel Modifier;
    private javax.swing.JLabel ModifierPrincipal;
    private javax.swing.JPanel Saisie;
    private javax.swing.JLabel SaisiePricipal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimized;
    // End of variables declaration//GEN-END:variables
}
