
import java.awt.Color;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author CHRISTIAN
 */



public class ConsultationPrincipal extends javax.swing.JFrame {
    Color DefaultColor,ClickedColor;
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    

// Dans votre constructeur ou méthode d'initialisation, initialisez ces composants
   

    /**
     * Creates new form ConsultationPrincipal
     */
    public ConsultationPrincipal() {
        super("Consultation");
        initComponents();
        AffichageDonneTable1();
       // connect=Gestionnaire_De_Connection.ConnctBD();
        
        DefaultColor=new Color(153, 0, 204);
        ClickedColor=new Color(1,128,128);
        //DefaultColor=new Color(13,36,51);
        //ClickedColor=new Color(240,151,57);
        
        // set default color to pan on run time
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(DefaultColor);
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(DefaultColor); 
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Modifier = new javax.swing.JPanel();
        ModifierPrincipal = new javax.swing.JLabel();
        Acceuil = new javax.swing.JPanel();
        AcceuilPrincipal = new javax.swing.JLabel();
        Saisie = new javax.swing.JPanel();
        SaisiePricipal = new javax.swing.JLabel();
        Consulte = new javax.swing.JPanel();
        ConsultationPrincipal = new javax.swing.JLabel();
        minimized = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        txtRecherche = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCopie = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnRechercher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_XING_100px.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, 159, 159));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LA MAIRIE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 186, 218, 35));

        Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ModifierMousePressed(evt);
            }
        });

        ModifierPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ModifierPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/modifier.png"))); // NOI18N
        ModifierPrincipal.setText("   Modifier");
        ModifierPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        ModifierPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierPrincipalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ModifierPrincipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ModifierLayout = new javax.swing.GroupLayout(Modifier);
        Modifier.setLayout(ModifierLayout);
        ModifierLayout.setHorizontalGroup(
            ModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ModifierPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ModifierLayout.setVerticalGroup(
            ModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ModifierPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(Modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 230, 60));

        Acceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AcceuilMousePressed(evt);
            }
        });

        AcceuilPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AcceuilPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AccueilBlanc.png"))); // NOI18N
        AcceuilPrincipal.setText("     Acceuil");
        AcceuilPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        AcceuilPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceuilPrincipalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AcceuilPrincipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout AcceuilLayout = new javax.swing.GroupLayout(Acceuil);
        Acceuil.setLayout(AcceuilLayout);
        AcceuilLayout.setHorizontalGroup(
            AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AcceuilLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AcceuilPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AcceuilLayout.setVerticalGroup(
            AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AcceuilPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(Acceuil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, 60));

        Saisie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SaisieMousePressed(evt);
            }
        });

        SaisiePricipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaisiePricipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/saisie.png"))); // NOI18N
        SaisiePricipal.setText("     Saisie");
        SaisiePricipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        SaisiePricipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaisiePricipalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SaisiePricipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout SaisieLayout = new javax.swing.GroupLayout(Saisie);
        Saisie.setLayout(SaisieLayout);
        SaisieLayout.setHorizontalGroup(
            SaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SaisieLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SaisiePricipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SaisieLayout.setVerticalGroup(
            SaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SaisiePricipal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(Saisie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 230, 60));

        Consulte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConsulteMousePressed(evt);
            }
        });

        ConsultationPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConsultationPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/consulte.png"))); // NOI18N
        ConsultationPrincipal.setText("    Consultation");
        ConsultationPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        ConsultationPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConsultationPrincipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ConsulteLayout = new javax.swing.GroupLayout(Consulte);
        Consulte.setLayout(ConsulteLayout);
        ConsulteLayout.setHorizontalGroup(
            ConsulteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsulteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ConsultationPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ConsulteLayout.setVerticalGroup(
            ConsulteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsultationPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(Consulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 230, 60));

        minimized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image/minimize.png"))); // NOI18N
        minimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizedMouseClicked(evt);
            }
        });

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image/close.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        txtRecherche.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRecherche.setForeground(new java.awt.Color(102, 102, 102));
        txtRecherche.setText("Nom_Personnel");
        txtRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRechercheKeyReleased(evt);
            }
        });

        TableCopie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableCopie);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("RETOUR");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("MODIFIER");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image/Print.png"))); // NOI18N
        jButton3.setText("IMPRIMER");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimized)
                        .addGap(15, 15, 15)
                        .addComponent(Exit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(490, 490, 490)
                                .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRechercher))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimized)
                    .addComponent(Exit))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRechercher, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(txtRecherche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ModifierPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierPrincipalMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_ModifierPrincipalMousePressed

    // Ajoutez un action listener au bouton de recherche
      
    private void ModifierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(DefaultColor);
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(ClickedColor);
    }//GEN-LAST:event_ModifierMousePressed

    private void AcceuilPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilPrincipalMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        Acceuil_principale ob= new Acceuil_principale();
        ob.setVisible(true);

    }//GEN-LAST:event_AcceuilPrincipalMouseClicked

    private void AcceuilPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilPrincipalMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_AcceuilPrincipalMousePressed

    private void AcceuilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(ClickedColor);
        Saisie.setBackground(DefaultColor);
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(DefaultColor);
    }//GEN-LAST:event_AcceuilMousePressed

    private void SaisiePricipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaisiePricipalMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        Saisie_copie_principal ob= new Saisie_copie_principal();
        ob.setVisible(true);
    }//GEN-LAST:event_SaisiePricipalMouseClicked

    private void SaisiePricipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaisiePricipalMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_SaisiePricipalMousePressed

    private void SaisieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaisieMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(ClickedColor);
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(DefaultColor);
    }//GEN-LAST:event_SaisieMousePressed

    private void ConsultationPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultationPrincipalMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_ConsultationPrincipalMousePressed

    private void ConsulteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsulteMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(DefaultColor);
        Consulte.setBackground(ClickedColor);
        Modifier.setBackground(DefaultColor);
    }//GEN-LAST:event_ConsulteMousePressed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void minimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizedMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizedMouseClicked

    private void ModifierPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierPrincipalMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        ModificationPrincipal ob=new ModificationPrincipal();
        ob.setVisible(true);
        
    }//GEN-LAST:event_ModifierPrincipalMouseClicked

     //fonction recherche
    private void txtRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyReleased
        // TODO add your handling code here:
        String searchString = txtRecherche.getText();
        rearch(searchString);
    }//GEN-LAST:event_txtRechercheKeyReleased

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
            // Connexion à la base de données
       conn = Gestionnaire_De_Connection.ConnctBD();

       try {
           // Vérification si une ligne est sélectionnée
           int selectedRow = TableCopie.getSelectedRow();
           if (selectedRow == -1) {
               JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne à supprimer.");
               return;
           }

           // Récupération de la valeur du champ REF de la ligne sélectionnée
           int refKopia = Integer.parseInt(TableCopie.getValueAt(selectedRow, 0).toString());

           // Suppression des informations dans la table 'kopia'
           String queryDeleteKopia = "DELETE FROM kopia WHERE REF = ?";
           PreparedStatement pstDeleteKopia = conn.prepareStatement(queryDeleteKopia);
           pstDeleteKopia.setInt(1, refKopia);
           pstDeleteKopia.executeUpdate();

           // Suppression des informations dans la table 'enfant' en utilisant ID_PARENTS associé à refKopia
           String queryDeleteEnfant = "DELETE FROM enfant WHERE ID_PARENTS = (SELECT ID_PARENTS FROM kopia WHERE REF = ?)";
           PreparedStatement pstDeleteEnfant = conn.prepareStatement(queryDeleteEnfant);
           pstDeleteEnfant.setInt(1, refKopia);
           pstDeleteEnfant.executeUpdate();

           // Suppression des informations dans la table 'parent' en utilisant ID_PARENT associé à refKopia
           String queryDeleteParent = "DELETE FROM parent WHERE ID_PARENT = (SELECT ID_PARENTS FROM kopia WHERE REF = ?)";
           PreparedStatement pstDeleteParent = conn.prepareStatement(queryDeleteParent);
           pstDeleteParent.setInt(1, refKopia);
           pstDeleteParent.executeUpdate();

           JOptionPane.showMessageDialog(this, "Les données ont été supprimées avec succès.");

           // Mise à jour de la table pour refléter la suppression
           ((DefaultTableModel) TableCopie.getModel()).removeRow(selectedRow);

           // Fermer les PreparedStatements
           pstDeleteKopia.close();
           pstDeleteEnfant.close();
           pstDeleteParent.close();

       } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(this, "Erreur de format de nombre. Assurez-vous que le champ REF est rempli correctement.");
       } catch (SQLException e) {
           e.printStackTrace();
           JOptionPane.showMessageDialog(this, "Erreur lors de la suppression des données.");
       } finally {
           try {
               if (conn != null) conn.close();
           } catch (SQLException e) {
               e.printStackTrace();
           }
       }
    }//GEN-LAST:event_jButton2MouseClicked
  
   public void rearch(String str){
       DefaultTableModel model;
       model= (DefaultTableModel)TableCopie.getModel();
       TableRowSorter<DefaultTableModel> trs= new TableRowSorter<>(model);
       TableCopie.setRowSorter(trs);
       trs.setRowFilter(RowFilter.regexFilter(str));
       
   }
    
    
    //affichage donnez dans la tableau
   public void AffichageDonneTable1() {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel();

    // Définition des colonnes du modèle de tableau
    model.addColumn("N°_COPIE");
    model.addColumn("DATE_CREAT");
    model.addColumn("NOM_ENF");
    model.addColumn("DATE_NAISS_ENF");
    model.addColumn("COMMUNE");
    model.addColumn("DISTRICT");
    model.addColumn("NOM_MERE");
    model.addColumn("NOM_PERE");
    model.addColumn("FOKONTANY");
    model.addColumn("RESPO");
    model.addColumn("ACTION"); // Colonne pour les boutons

    // Requête pour obtenir les données
    String requetListCopie = "SELECT cop.ref AS N°_COPIE, cop.date_creation AS DATE_CREAT, " +
                             "CONCAT(enf.prenom, ' ', enf.nom) AS NOM_ENF, enf.date_naissance AS DATE_NAISS_ENF, " +
                             "cop.lieu_creation AS COMMUNE, enf.district AS DISTRICT, " +
                             "par.nom_mere AS NOM_MERE, par.nom_pere AS NOM_PERE, " +
                             "cop.lieu_creation AS FOKONTANY, cop.responsable AS RESPO " +
                             "FROM kopia cop " +
                             "INNER JOIN enfant enf ON cop.ID_PARENTS = enf.ID_PARENT " +
                             "INNER JOIN parent par ON par.ID_PARENT = enf.ID_PARENT";

    try {
        con = Gestionnaire_De_Connection.ConnctBD();
        Statement stmtListCopie = con.createStatement();
        rs = stmtListCopie.executeQuery(requetListCopie);

        // Format de date attendu
        SimpleDateFormat inputDateFormat = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MM-yyyy");

        // Parcours des résultats et ajout des lignes au modèle de tableau
        while (rs.next()) {
            Date dateCreat = inputDateFormat.parse(rs.getString("DATE_CREAT"));
            Date dateNaissEnf = inputDateFormat.parse(rs.getString("DATE_NAISS_ENF"));

            // Création des boutons
            JButton btnPrint = new JButton("Imprimer");
            JButton btnEdit = new JButton("Modifier");
            JButton btnDelete = new JButton("Supprimer");

            // Ajouter des écouteurs d'événements pour les boutons
            //btnPrint.addActionListener(e -> {
                // Code pour imprimer les données
             //   System.out.println("Imprimer pour : " + rs.getInt("N°_COPIE"));
           // });

          //  btnEdit.addActionListener(e -> {
                // Code pour modifier les données
              //  System.out.println("Modifier pour : " + rs.getInt("N°_COPIE"));
           // });

          //  btnDelete.addActionListener(e -> {
                // Code pour supprimer les données
            //    System.out.println("Supprimer pour : " + rs.getInt("N°_COPIE"));
           // });

            model.addRow(new Object[]{
                rs.getInt("N°_COPIE"),
                outputDateFormat.format(dateCreat),
                rs.getString("NOM_ENF"),
                outputDateFormat.format(dateNaissEnf),
                rs.getString("COMMUNE"),
                rs.getString("DISTRICT"),
                rs.getString("NOM_MERE"),
                rs.getString("NOM_PERE"),
                rs.getString("FOKONTANY"),
                rs.getString("RESPO"),
                // Ajouter les boutons à la colonne ACTION
                btnPrint,
                btnEdit,
                btnDelete
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    } catch (ParseException e) {
        e.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Affectation du modèle au tableau
    TableCopie.setModel(model);
}
   
 


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultationPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultationPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultationPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultationPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultationPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acceuil;
    private javax.swing.JLabel AcceuilPrincipal;
    private javax.swing.JLabel ConsultationPrincipal;
    private javax.swing.JPanel Consulte;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel Modifier;
    private javax.swing.JLabel ModifierPrincipal;
    private javax.swing.JPanel Saisie;
    private javax.swing.JLabel SaisiePricipal;
    private javax.swing.JTable TableCopie;
    private javax.swing.JButton btnRechercher;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimized;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
