
import java.sql.*;
import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author CHRISTIAN
 */
public class Saisie_copie_principal extends javax.swing.JFrame {
    Color DefaultColor,ClickedColor;
    //PreparedStatement pstmt;
   // Gestionnaire_De_Connection maConnexion =new Gestionnaire_De_Connection();
    Connection conn;
    ResultSet rs=null;
    PreparedStatement pstParent=null;
    PreparedStatement pstEnfant=null;
    PreparedStatement pstCopie=null;
    

    /**
     * Creates new form Saisie_copie_principal
     */
    public Saisie_copie_principal() {
        super("Gestion_copie");
        
        initComponents();
        //RandomRef_Copie();
        Calender();
        //declaration champ des clée primaire
        jText_Idenfants.setVisible(false);
        jText_Idparent.setVisible(false);
        jText_ref.setVisible(false);
        
        
        DefaultColor=new Color(153, 0, 204);
        ClickedColor=new Color(1,128,128);
        //DefaultColor=new Color(13,36,51);
        //ClickedColor=new Color(240,151,57);
        
        // set default color to pan on run time
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(DefaultColor);
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(DefaultColor); 
        
        //creta a button group for the radiobuton
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton_home);
        bg.add(jRadioButton_femme);
    }
    // public void RandomRef_Copie(){
      // Random ra=new Random();
      //  RefCopie.setText(""+ra.nextInt(10+1));
    //}
     // Enfant_naitre
     public void Calender(){
         //create date automatical
         Calendar cal=new GregorianCalendar();
         int month=cal.get(Calendar.MONTH);
         int year=cal.get(Calendar.YEAR);
         int day=cal.get(Calendar.DAY_OF_MONTH);
        jTextDate_Create.setText(+day+"/"+(month+1)+"/"+year);
        
        //create time automatical
        int second=cal.get(Calendar.SECOND);
        int minute=cal.get(Calendar.MINUTE);
        int hour=cal.get(Calendar.HOUR_OF_DAY);
        HeurCreatCopie.setText(hour+":"+minute+":"+second);
        
    }
    
     
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        minimized = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Modifier = new javax.swing.JPanel();
        ModifierPrincipal = new javax.swing.JLabel();
        Acceuil = new javax.swing.JPanel();
        AcceuilPrincipal = new javax.swing.JLabel();
        Saisie = new javax.swing.JPanel();
        SaisiePricipal = new javax.swing.JLabel();
        Consulte = new javax.swing.JPanel();
        ConsultationPrincipal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextNomEnfant = new javax.swing.JTextField();
        jTextPrenomEnfant = new javax.swing.JTextField();
        jTextCituatEnfant = new javax.swing.JTextField();
        heur_naitreEnfant = new javax.swing.JFormattedTextField();
        jRadioButton_home = new javax.swing.JRadioButton();
        jRadioButton_femme = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jTextDistrict = new javax.swing.JTextField();
        Date_naitreEnfant = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextDate_Create = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextCituatCreat = new javax.swing.JTextField();
        jTextLieuCreat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextRespo = new javax.swing.JTextField();
        HeurCreatCopie = new javax.swing.JFormattedTextField();
        jText_Idenfants = new javax.swing.JTextField();
        jText_Idparent = new javax.swing.JTextField();
        jText_ref = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextNompere = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextPrenompere = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextLieuNaitrepere = new javax.swing.JTextField();
        dateNaitrepere = new javax.swing.JFormattedTextField();
        jTextProffepere = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextNommere = new javax.swing.JTextField();
        jTextPrenommere = new javax.swing.JTextField();
        dateNaitremere = new javax.swing.JFormattedTextField();
        jTextLieuNaitremere = new javax.swing.JTextField();
        jTextProffemere = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextResidence = new javax.swing.JTextField();
        Ajoute_Touts = new javax.swing.JToggleButton();
        retournAcceuil = new javax.swing.JToggleButton();
        mettre_ajours = new javax.swing.JButton();
        jTextRecherche = new javax.swing.JTextField();
        jButtonRechercheEtRecuperation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image/minimize.png"))); // NOI18N
        minimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizedMouseClicked(evt);
            }
        });
        jPanel1.add(minimized, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, -1, -1));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image/close.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_XING_100px.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, 159, 159));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LA MAIRIE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 186, 218, 35));

        Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ModifierMousePressed(evt);
            }
        });

        ModifierPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ModifierPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/modifier.png"))); // NOI18N
        ModifierPrincipal.setText("   Modifier");
        ModifierPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        ModifierPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierPrincipalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ModifierPrincipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ModifierLayout = new javax.swing.GroupLayout(Modifier);
        Modifier.setLayout(ModifierLayout);
        ModifierLayout.setHorizontalGroup(
            ModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ModifierPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ModifierLayout.setVerticalGroup(
            ModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ModifierPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(Modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 230, 60));

        Acceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AcceuilMousePressed(evt);
            }
        });

        AcceuilPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AcceuilPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AccueilBlanc.png"))); // NOI18N
        AcceuilPrincipal.setText("     Acceuil");
        AcceuilPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        AcceuilPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceuilPrincipalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AcceuilPrincipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout AcceuilLayout = new javax.swing.GroupLayout(Acceuil);
        Acceuil.setLayout(AcceuilLayout);
        AcceuilLayout.setHorizontalGroup(
            AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AcceuilLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AcceuilPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AcceuilLayout.setVerticalGroup(
            AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AcceuilPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(Acceuil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, 60));

        Saisie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SaisieMousePressed(evt);
            }
        });

        SaisiePricipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaisiePricipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/saisie.png"))); // NOI18N
        SaisiePricipal.setText("     Saisie");
        SaisiePricipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        SaisiePricipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SaisiePricipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout SaisieLayout = new javax.swing.GroupLayout(Saisie);
        Saisie.setLayout(SaisieLayout);
        SaisieLayout.setHorizontalGroup(
            SaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SaisieLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SaisiePricipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SaisieLayout.setVerticalGroup(
            SaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SaisiePricipal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(Saisie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 230, 60));

        Consulte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConsulteMousePressed(evt);
            }
        });

        ConsultationPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConsultationPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/consulte.png"))); // NOI18N
        ConsultationPrincipal.setText("    Consultation");
        ConsultationPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        ConsultationPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultationPrincipalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConsultationPrincipalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ConsulteLayout = new javax.swing.GroupLayout(Consulte);
        Consulte.setLayout(ConsulteLayout);
        ConsulteLayout.setHorizontalGroup(
            ConsulteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsulteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ConsultationPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ConsulteLayout.setVerticalGroup(
            ConsulteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsultationPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(Consulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 230, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 730));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORMULAIRE_ENFANT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("NOM");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, 40));

        jLabel6.setText("PRENOM");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 159, 40));

        jLabel7.setText("DATE DE NAISSANCE");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 159, 40));

        jLabel8.setText("SEXE");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 20));

        jLabel9.setText("HEURE_NAISSANCE");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 40));

        jLabel10.setText("CITUATION_NAISSANCE");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 40));

        jTextNomEnfant.setToolTipText("Entrer nom Enfant");
        jPanel3.add(jTextNomEnfant, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 215, 40));
        jPanel3.add(jTextPrenomEnfant, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 215, 40));
        jPanel3.add(jTextCituatEnfant, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 215, 40));

        heur_naitreEnfant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm:ss"))));
        heur_naitreEnfant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        heur_naitreEnfant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heur_naitreEnfantKeyTyped(evt);
            }
        });
        jPanel3.add(heur_naitreEnfant, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 215, 40));

        jRadioButton_home.setText("Homme");
        jPanel3.add(jRadioButton_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, 20));

        jRadioButton_femme.setText("Femme");
        jPanel3.add(jRadioButton_femme, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, 20));

        jLabel21.setText("DISTRICT");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, 40));

        jTextDistrict.setToolTipText("District d'enfant née");
        jPanel3.add(jTextDistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 215, 40));

        try {
            Date_naitreEnfant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Date_naitreEnfant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(Date_naitreEnfant, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 215, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 430, 380));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CITUATION_COPIE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 0, 153))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("DATE_CREATE");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 105, 30));
        jPanel4.add(jTextDate_Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 196, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("HEURE_CREATE");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("CITUAT_CREAT");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 40));
        jPanel4.add(jTextCituatCreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 162, 196, 40));
        jPanel4.add(jTextLieuCreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 196, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("LIEU_CREATE");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 112, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("RESPONSABLE");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 105, 40));
        jPanel4.add(jTextRespo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 196, 40));

        HeurCreatCopie.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        HeurCreatCopie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HeurCreatCopieMouseEntered(evt);
            }
        });
        jPanel4.add(HeurCreatCopie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 196, 40));
        jPanel4.add(jText_Idenfants, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 100, 40));
        jPanel4.add(jText_Idparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 90, 40));
        jPanel4.add(jText_ref, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 160, 90, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 670, 210));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image/sep2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 20, 380));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORMULAIRE_PARENTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("NOM_PERE");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 108, 40));
        jPanel5.add(jTextNompere, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 160, 40));

        jLabel12.setText("PRENOM_PERE");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 111, 40));
        jPanel5.add(jTextPrenompere, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, 40));

        jLabel13.setText("DATE DE NAISS_PERE");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 40));

        jLabel14.setText("LIEU_NAISS_PERE");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 111, 40));
        jPanel5.add(jTextLieuNaitrepere, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, 40));

        try {
            dateNaitrepere.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dateNaitrepere.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(dateNaitrepere, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 160, 40));
        jPanel5.add(jTextProffepere, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 160, 40));

        jLabel22.setText("PROFESS_PERE");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 111, 40));
        jPanel5.add(jTextNommere, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 160, 40));
        jPanel5.add(jTextPrenommere, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 160, 40));

        try {
            dateNaitremere.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dateNaitremere.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(dateNaitremere, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 160, 40));
        jPanel5.add(jTextLieuNaitremere, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 160, 40));
        jPanel5.add(jTextProffemere, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 160, 40));

        jLabel23.setText("NOM_MERE");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 108, 40));

        jLabel24.setText("PRENOM_MERE");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 111, 40));

        jLabel25.setText("DATE DE NAISS_MERE");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 40));

        jLabel26.setText("LIEU_NAISS_MERE");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 111, 40));

        jLabel27.setText("PROFESS_MERE");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 111, 40));

        jLabel28.setText("RESIDENCE");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 111, 40));
        jPanel5.add(jTextResidence, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 190, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 610, 390));

        Ajoute_Touts.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ajoute_Touts.setForeground(new java.awt.Color(0, 0, 102));
        Ajoute_Touts.setText("AJOUTE");
        Ajoute_Touts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        Ajoute_Touts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajoute_ToutsActionPerformed(evt);
            }
        });
        jPanel1.add(Ajoute_Touts, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, 170, 40));

        retournAcceuil.setForeground(new java.awt.Color(0, 0, 102));
        retournAcceuil.setText("RETOUR");
        retournAcceuil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        retournAcceuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retournAcceuilActionPerformed(evt);
            }
        });
        jPanel1.add(retournAcceuil, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, 130, 40));

        mettre_ajours.setText("UPDATE");
        mettre_ajours.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 153), 2, true));
        mettre_ajours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mettre_ajoursMouseClicked(evt);
            }
        });
        jPanel1.add(mettre_ajours, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 680, 160, 40));

        jTextRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextRechercheKeyReleased(evt);
            }
        });
        jPanel1.add(jTextRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 160, 30));

        jButtonRechercheEtRecuperation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image/search.png"))); // NOI18N
        jButtonRechercheEtRecuperation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRechercheEtRecuperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechercheEtRecuperationActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRechercheEtRecuperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Recherche");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void ModifierPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierPrincipalMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_ModifierPrincipalMousePressed

    private void ModifierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(DefaultColor);
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(ClickedColor);
    }//GEN-LAST:event_ModifierMousePressed

    private void AcceuilPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilPrincipalMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_AcceuilPrincipalMousePressed

    private void AcceuilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(ClickedColor);
        Saisie.setBackground(DefaultColor);
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(DefaultColor);
    }//GEN-LAST:event_AcceuilMousePressed

    private void SaisiePricipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaisiePricipalMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_SaisiePricipalMousePressed

    private void SaisieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaisieMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(ClickedColor);
        Consulte.setBackground(DefaultColor);
        Modifier.setBackground(DefaultColor);
    }//GEN-LAST:event_SaisieMousePressed

    private void ConsultationPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultationPrincipalMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_ConsultationPrincipalMousePressed

    private void ConsulteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsulteMousePressed
        // TODO add your handling code here:
        Acceuil.setBackground(DefaultColor);
        Saisie.setBackground(DefaultColor);
        Consulte.setBackground(ClickedColor);
        Modifier.setBackground(DefaultColor);
    }//GEN-LAST:event_ConsulteMousePressed

    private void retournAcceuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retournAcceuilActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Acceuil_principale ob= new Acceuil_principale();
        ob.setVisible(true); 
        
    }//GEN-LAST:event_retournAcceuilActionPerformed
//insertion enfant
    
    
    
    
//insertion donne dans le database
    private void Ajoute_ToutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajoute_ToutsActionPerformed
      // Déclaration des informations parents
    String NomPere = jTextNompere.getText(); 
    String Prenompere = jTextPrenompere.getText();
    String datepere = dateNaitrepere.getText();
    String LieuNaitrepere = jTextLieuNaitrepere.getText();
    String Proffepere = jTextProffepere.getText();
    String Nommere = jTextNommere.getText();
    String Prenommere = jTextPrenommere.getText();
    String datemere = dateNaitremere.getText();
    String LieuNaitremere = jTextLieuNaitremere.getText();
    String Proffemere = jTextProffemere.getText();
    String Residence = jTextResidence.getText();
    
    // Déclaration des informations enfants
    String AnaranaZAZA = jTextNomEnfant.getText();
    String Fanampiny = jTextPrenomEnfant.getText();
    String Fahaterahana = Date_naitreEnfant.getText();
    String Ora = heur_naitreEnfant.getText();
    String Fepetra = jTextCituatEnfant.getText();
    String Disitrika = jTextDistrict.getText();
    String Genre = jRadioButton_femme.isSelected() ? "Zaza vavy" : "zaza lahy";
    
    // Déclaration des informations copie
    String Date_fanamboarana = jTextDate_Create.getText();
    String fotoana = HeurCreatCopie.getText();
    String fombafomba = jTextCituatCreat.getText();
    String toerana = jTextLieuCreat.getText();
    String Mpiandraikitra = jTextRespo.getText();
    
    Connection conn = null;
    PreparedStatement pstParent = null;
    PreparedStatement pstEnfant = null;
    PreparedStatement pstCopie = null;
    ResultSet rs = null;
    ResultSet rsEnfant = null;

    try {
        // Gestionnaire de connexion
        conn = Gestionnaire_De_Connection.ConnctBD();
        
        // Insertion des parents et récupération de l'ID généré
        pstParent = conn.prepareStatement("INSERT INTO parent(nom_pere, prenom_pere, date_naissance_pere, lieu_naissance_pere, profession_pere, nom_mere, prenom_mere, date_naissance_mere, lieu_naissance_mere, profession_mere, residence) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS);
        pstParent.setString(1, NomPere);
        pstParent.setString(2, Prenompere);
        pstParent.setString(3, datepere);
        pstParent.setString(4, LieuNaitrepere);
        pstParent.setString(5, Proffepere);
        pstParent.setString(6, Nommere);
        pstParent.setString(7, Prenommere);
        pstParent.setString(8, datemere);
        pstParent.setString(9, LieuNaitremere);
        pstParent.setString(10, Proffemere);
        pstParent.setString(11, Residence);
        pstParent.executeUpdate();
        
        // Récupérer l'ID du parent inséré
        rs = pstParent.getGeneratedKeys();
        int parentId = -1;
        if (rs.next()) {
            parentId = rs.getInt(1);
        }
        
        // Réinitialisation des champs texte pour les parents
        jTextNompere.setText(""); 
        jTextPrenompere.setText("");
        dateNaitrepere.setText("");
        jTextLieuNaitrepere.setText("");
        jTextProffepere.setText("");
        jTextNommere.setText("");
        jTextPrenommere.setText("");
        dateNaitremere.setText("");
        jTextLieuNaitremere.setText("");
        jTextProffemere.setText("");
        jTextResidence.setText("");
        
        // Insertion des enfants avec l'ID parent et récupération de l'ID généré de l'enfant
        pstEnfant = conn.prepareStatement("INSERT INTO enfant(nom, prenom, date_naissance, heure_naissance, situation_naissance, district, sexe, ID_PARENT) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS);
        pstEnfant.setString(1, AnaranaZAZA);
        pstEnfant.setString(2, Fanampiny);
        pstEnfant.setString(3, Fahaterahana);
        pstEnfant.setString(4, Ora);
        pstEnfant.setString(5, Fepetra);
        pstEnfant.setString(6, Disitrika);
        pstEnfant.setString(7, Genre);
        pstEnfant.setInt(8, parentId);
        pstEnfant.executeUpdate();
        
        // Récupérer l'ID de l'enfant inséré
        rsEnfant = pstEnfant.getGeneratedKeys();
        int enfantId = -1;
        if (rsEnfant.next()) {
            enfantId = rsEnfant.getInt(1);
        }
        
        // Réinitialisation des champs texte pour les enfants
        jTextNomEnfant.setText("");
        jTextPrenomEnfant.setText("");
        Date_naitreEnfant.setText("");
        heur_naitreEnfant.setText("");
        jTextCituatEnfant.setText("");
        jTextDistrict.setText("");
        
        // Insertion des copies avec l'ID enfant
        pstCopie = conn.prepareStatement("INSERT INTO kopia(date_creation, heure_creation, situation_creation, lieu_creation, responsable, ID_PARENTS) VALUES (?, ?, ?, ?, ?, ?)");
        pstCopie.setString(1, Date_fanamboarana);
        pstCopie.setString(2, fotoana);
        pstCopie.setString(3, fombafomba);
        pstCopie.setString(4, toerana);
        pstCopie.setString(5, Mpiandraikitra);
        pstCopie.setInt(6, enfantId);
        pstCopie.executeUpdate();
        
        // Réinitialisation des champs texte pour les copies
        //jTextDate_Create.setText("");
        //HeurCreatCopie.setText("");
        jTextCituatCreat.setText("");
        jTextLieuCreat.setText("");
        jTextRespo.setText("");
        
    } catch (SQLException ex) {
        System.out.println("Erreur lors de l'insertion des parents: " + ex.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (rsEnfant != null) rsEnfant.close();
            if (pstParent != null) pstParent.close();
            if (pstEnfant != null) pstEnfant.close();
            if (pstCopie != null) pstCopie.close();
            if (conn != null) conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
        
    }//GEN-LAST:event_Ajoute_ToutsActionPerformed

    //insertion enfant dans un table
    
    
    private void minimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizedMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizedMouseClicked

    private void AcceuilPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilPrincipalMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        Acceuil_principale ob=new Acceuil_principale();
        ob.setVisible(true);
    }//GEN-LAST:event_AcceuilPrincipalMouseClicked

    private void ConsultationPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultationPrincipalMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        ConsultationPrincipal ob=new ConsultationPrincipal();
        ob.setVisible(true);
    }//GEN-LAST:event_ConsultationPrincipalMouseClicked

    private void ModifierPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierPrincipalMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        ModificationPrincipal ob=new ModificationPrincipal();
        ob.setVisible(true);
    }//GEN-LAST:event_ModifierPrincipalMouseClicked

    private void heur_naitreEnfantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heur_naitreEnfantKeyTyped
       
    }//GEN-LAST:event_heur_naitreEnfantKeyTyped

    private void HeurCreatCopieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeurCreatCopieMouseEntered
        // TODO add your handling code here:
        //DateTime();
    }//GEN-LAST:event_HeurCreatCopieMouseEntered

    //fonction recherche par id_parents
    private void jTextRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRechercheKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextRechercheKeyReleased

    private void jButtonRechercheEtRecuperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechercheEtRecuperationActionPerformed
        // TODO add your handling code here:
         rechercheDonnees();
    }//GEN-LAST:event_jButtonRechercheEtRecuperationActionPerformed

    //mis a jours les donner
    private void mettre_ajoursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mettre_ajoursMouseClicked
        // TODO add your handling code here:
       conn = Gestionnaire_De_Connection.ConnctBD();

    try {
        // Vérification des champs avant la conversion
        if (jText_Idenfants.getText().isEmpty() || jText_Idparent.getText().isEmpty() || jText_ref.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs requis avant de mettre à jour.");
            return; // Sortir de la méthode si un champ est vide
        }

        // Conversion des champs en entiers après la vérification
        int idParents = Integer.parseInt(jText_Idenfants.getText());
        int idParent = Integer.parseInt(jText_Idparent.getText());
        int refKopia = Integer.parseInt(jText_ref.getText());

        // Mise à jour des informations dans la table 'parent'
        String queryParent = "UPDATE parent SET nom_pere = ?, prenom_pere = ?, date_naissance_pere = ?, lieu_naissance_pere = ?, " +
                             "profession_pere = ?, nom_mere = ?, prenom_mere = ?, date_naissance_mere = ?, lieu_naissance_mere = ?, " +
                             "profession_mere = ?, residence = ? WHERE ID_PARENT = ?";

        PreparedStatement pstParent = conn.prepareStatement(queryParent);
        pstParent.setString(1, jTextNompere.getText());
        pstParent.setString(2, jTextPrenompere.getText());
        pstParent.setString(3, dateNaitrepere.getText());
        pstParent.setString(4, jTextLieuNaitrepere.getText());
        pstParent.setString(5, jTextProffepere.getText());
        pstParent.setString(6, jTextNommere.getText());
        pstParent.setString(7, jTextPrenommere.getText());
        pstParent.setString(8, dateNaitremere.getText());
        pstParent.setString(9, jTextLieuNaitremere.getText());
        pstParent.setString(10, jTextProffemere.getText());
        pstParent.setString(11, jTextResidence.getText());
        pstParent.setInt(12, idParent); // Ajoutez l'ID_PARENT ici

        pstParent.executeUpdate();

        // Mise à jour des informations dans la table 'kopia'
        String queryKopia = "UPDATE kopia SET date_creation = ?, heure_creation = ?, situation_creation = ?, lieu_creation = ?, " +
                            "responsable = ? WHERE REF = ?";

        PreparedStatement pstKopia = conn.prepareStatement(queryKopia);
        pstKopia.setString(1, jTextDate_Create.getText());
        pstKopia.setString(2, HeurCreatCopie.getText());
        pstKopia.setString(3, jTextCituatCreat.getText());
        pstKopia.setString(4, jTextLieuCreat.getText());
        pstKopia.setString(5, jTextRespo.getText());
        pstKopia.setInt(6, refKopia); // Ajoutez le REF ici

        pstKopia.executeUpdate();

        // Mise à jour des informations dans la table 'enfant'
        String queryEnfant = "UPDATE enfant SET nom = ?, prenom = ?, date_naissance = ?, district = ?, sexe = ? WHERE ID_PARENTS = ?";

        PreparedStatement pstEnfant = conn.prepareStatement(queryEnfant);
        pstEnfant.setString(1, jTextNomEnfant.getText());
        pstEnfant.setString(2, jTextPrenomEnfant.getText());
        pstEnfant.setString(3, Date_naitreEnfant.getText());
        pstEnfant.setString(4, jTextDistrict.getText());
        pstEnfant.setString(5, jRadioButton_femme.isSelected() ? "zaza vavy" : "zaza lahy"); // Assurez-vous que le sexe est correctement géré
        pstEnfant.setInt(6, idParents); // Ajoutez l'ID_PARENTS ici

        pstEnfant.executeUpdate();

        JOptionPane.showMessageDialog(this, "Les données ont été mises à jour avec succès.");

        // Fermer les PreparedStatements
        pstParent.close();
        pstKopia.close();
        pstEnfant.close();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Erreur de format de nombre. Assurez-vous que les champs ID_PARENT et REF sont remplis correctement.");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors de la mise à jour des données.");
    }
    }//GEN-LAST:event_mettre_ajoursMouseClicked

    private void rechercheDonnees() {
    conn = Gestionnaire_De_Connection.ConnctBD();
    int idParents = Integer.parseInt(jTextRecherche.getText());

    try {
        String query = "SELECT p.ID_PARENT, p.nom_pere, p.prenom_pere, p.date_naissance_pere, p.lieu_naissance_pere, " +
                       "p.profession_pere, p.nom_mere, p.prenom_mere, p.date_naissance_mere, p.lieu_naissance_mere, " +
                       "p.profession_mere, p.residence, k.date_creation, k.heure_creation, k.situation_creation, " +
                       "k.REF, k.lieu_creation, k.responsable, e.nom AS nom_enfant, e.prenom AS prenom_enfant, " +
                       "e.ID_PARENTS, e.date_naissance AS date_naissance_enfant,e.heure_naissance AS heure_naissance_enfant,e.situation_naissance AS situation_naissance_enfant, e.district AS lieu_naissance_enfant, e.sexe AS sexe_enfant " +
                       "FROM parent p " +
                       "INNER JOIN kopia k ON p.ID_PARENT = k.REF " +
                       "INNER JOIN enfant e ON p.ID_PARENT = e.ID_PARENTS " +
                       "WHERE p.ID_PARENT = ?";

        PreparedStatement pst = conn.prepareStatement(query);
        pst.setInt(1, idParents);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            // Informations sur les parents
            jTextNompere.setText(rs.getString("nom_pere"));
            jTextPrenompere.setText(rs.getString("prenom_pere"));
            dateNaitrepere.setText(rs.getString("date_naissance_pere"));
            jTextLieuNaitrepere.setText(rs.getString("lieu_naissance_pere"));
            jTextProffepere.setText(rs.getString("profession_pere"));
            jTextNommere.setText(rs.getString("nom_mere"));
            jTextPrenommere.setText(rs.getString("prenom_mere"));
            dateNaitremere.setText(rs.getString("date_naissance_mere"));
            jTextLieuNaitremere.setText(rs.getString("lieu_naissance_mere"));
            jTextProffemere.setText(rs.getString("profession_mere"));
            jTextResidence.setText(rs.getString("residence"));
            jText_Idparent.setText(rs.getString("ID_PARENT"));

            // Informations sur la copie
            jTextDate_Create.setText(rs.getString("date_creation"));
            HeurCreatCopie.setText(rs.getString("heure_creation"));
            jTextCituatCreat.setText(rs.getString("situation_creation"));
            jTextLieuCreat.setText(rs.getString("lieu_creation"));
            jTextRespo.setText(rs.getString("responsable"));
            jText_ref.setText(rs.getString("REF"));
            
            // Informations sur l'enfant
            jTextNomEnfant.setText(rs.getString("nom_enfant"));
            jTextPrenomEnfant.setText(rs.getString("prenom_enfant"));
            Date_naitreEnfant.setText(rs.getString("date_naissance_enfant"));
            heur_naitreEnfant.setText(rs.getString("heure_naissance_enfant"));
            jTextCituatEnfant.setText(rs.getString("situation_naissance_enfant"));
            jTextDistrict.setText(rs.getString("lieu_naissance_enfant"));
            jRadioButton_femme.setText(rs.getString("sexe_enfant"));
            jText_Idenfants.setText(rs.getString("ID_PARENTS"));
        } else {
            JOptionPane.showMessageDialog(this, "Aucun enregistrement trouvé pour l'ID_PARENTS donné.");
        }

        rs.close();
        pst.close();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors de la recherche des données.");
    }
}
    /*private void txtRechercheKeyReleased(java.awt.event.KeyEvent evt) {                                         
        // TODO add your handling code here:
        String searchString = txtRecherche.getText();
        rearch(searchString);
    }                                        
  
   public void rearch(String str){
       DefaultTableModel model;
       model= (DefaultTableModel)TableCopie.getModel();
       TableRowSorter<DefaultTableModel> trs= new TableRowSorter<>(model);
       TableCopie.setRowSorter(trs);
       trs.setRowFilter(RowFilter.regexFilter(str));
       
   }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saisie_copie_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saisie_copie_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saisie_copie_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saisie_copie_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saisie_copie_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acceuil;
    private javax.swing.JLabel AcceuilPrincipal;
    private javax.swing.JToggleButton Ajoute_Touts;
    private javax.swing.JLabel ConsultationPrincipal;
    private javax.swing.JPanel Consulte;
    private javax.swing.JFormattedTextField Date_naitreEnfant;
    private javax.swing.JLabel Exit;
    private javax.swing.JFormattedTextField HeurCreatCopie;
    private javax.swing.JPanel Modifier;
    private javax.swing.JLabel ModifierPrincipal;
    private javax.swing.JPanel Saisie;
    private javax.swing.JLabel SaisiePricipal;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField dateNaitremere;
    private javax.swing.JFormattedTextField dateNaitrepere;
    private javax.swing.JFormattedTextField heur_naitreEnfant;
    private javax.swing.JButton jButtonRechercheEtRecuperation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton_femme;
    private javax.swing.JRadioButton jRadioButton_home;
    private javax.swing.JTextField jTextCituatCreat;
    private javax.swing.JTextField jTextCituatEnfant;
    private javax.swing.JTextField jTextDate_Create;
    private javax.swing.JTextField jTextDistrict;
    private javax.swing.JTextField jTextLieuCreat;
    private javax.swing.JTextField jTextLieuNaitremere;
    private javax.swing.JTextField jTextLieuNaitrepere;
    private javax.swing.JTextField jTextNomEnfant;
    private javax.swing.JTextField jTextNommere;
    private javax.swing.JTextField jTextNompere;
    private javax.swing.JTextField jTextPrenomEnfant;
    private javax.swing.JTextField jTextPrenommere;
    private javax.swing.JTextField jTextPrenompere;
    private javax.swing.JTextField jTextProffemere;
    private javax.swing.JTextField jTextProffepere;
    private javax.swing.JTextField jTextRecherche;
    private javax.swing.JTextField jTextResidence;
    private javax.swing.JTextField jTextRespo;
    private javax.swing.JTextField jText_Idenfants;
    private javax.swing.JTextField jText_Idparent;
    private javax.swing.JTextField jText_ref;
    private javax.swing.JButton mettre_ajours;
    private javax.swing.JLabel minimized;
    private javax.swing.JToggleButton retournAcceuil;
    // End of variables declaration//GEN-END:variables
}
